apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-app-mysql-deployment
  template:
    metadata:
      labels:
        app: employee-app-mysql-deployment
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DATABASE
          value: "employeedb"
