apiVersion: apps/V1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: yugal47/employee-app:v0.0.1
        ports:
        - containerPort: 80
